openapi: 3.0.3
info:
  title: GCP Release Notes
  description: |-
    This is a sample demo API to interact with BigQuery as backend and format a response
    message.
  contact:
    email: nobody@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.14
servers:
  - url: https://apigee-34-29-171-212.sslip.io/gcpreleases/v1
    description: Production Server
  - url: https://apigee-34-29-171-212.sslip.io/eval/gcpreleases/v1
    description: Evaluation/QA Server
paths:
  /releases:
    get:
      summary: List 5 most recent release notes.
      operationId: getReleases
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReleaseInfo'
  /echo:
    get:
      summary: Returns information about the data sent in the request using the Mock API
      operationId: getEcho
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoInfo'
    post:
      summary: Returns information about the data sent in the request using the Mock API
      operationId: postEcho
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoInfo'

components:
  schemas:
    ReleaseInfo:
      type: object
      properties:
        description:
          type: string
        noteType:
          type: string
        productName:
          type: string
        publishedAt:
          type: string
          format: date-time
    EchoInfo:
      type: object
      properties:
        args:
          type: object
        body:
          type: string
        headers:
          type: object
        method:
          type: string
        url:
          type: string
